// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiWvtvF_RvGN1WB2AMxCwvV0y1jwcWvtU',
    appId: '1:845932372806:web:293862d7e42c9893c43b47',
    messagingSenderId: '845932372806',
    projectId: 'final-project-2138d',
    authDomain: 'final-project-2138d.firebaseapp.com',
    storageBucket: 'final-project-2138d.appspot.com',
    measurementId: 'G-N0GN8VF41Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ1r2aQyxyZ-MxmSF-LLAWtBJKe0SM-vw',
    appId: '1:845932372806:android:db3664ac308d6169c43b47',
    messagingSenderId: '845932372806',
    projectId: 'final-project-2138d',
    storageBucket: 'final-project-2138d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW_H0p-_tjmbIV_MJ4Ic4DINdmbJOboQY',
    appId: '1:845932372806:ios:318d21e6a269e68bc43b47',
    messagingSenderId: '845932372806',
    projectId: 'final-project-2138d',
    storageBucket: 'final-project-2138d.appspot.com',
    iosBundleId: 'com.example.animation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW_H0p-_tjmbIV_MJ4Ic4DINdmbJOboQY',
    appId: '1:845932372806:ios:de7ed6069d2288bac43b47',
    messagingSenderId: '845932372806',
    projectId: 'final-project-2138d',
    storageBucket: 'final-project-2138d.appspot.com',
    iosBundleId: 'com.example.animation.RunnerTests',
  );
}
